version: "3"
services:
    db:
        image: "microsoft/mssql-server-linux:2017-latest"
        environment:
            SA_PASSWORD: "TheFalcon123"
            ACCEPT_EULA: "Y"
            ASPNETCORE_ENVIRONMENT: "docker"
            MSSQL_PID: "Express"
        ports:
            - "1433:1433"
        volumes:
            - "dbdata_authority:/tmp/authority"
        depends_on:
            - authority
        command:
            - /bin/sh
            - -c
            - |
                sleep 15s && /tmp/authority/authority.sh & /opt/mssql/bin/sqlservr
    authority:
        image: "owlvey/authority:latest"
        environment:
            ASPNETCORE_ENVIRONMENT: "docker"
        ports:
            - "45001:80"
        volumes:
            - "dbdata_authority:/app/data"
volumes:
  dbdata_authority: