name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: commit
  jobs:    
  - job:    
    pool:
      vmImage: 'ubuntu-latest'        
    steps:
    - checkout: self        
    - task: RegexReplace@3
      inputs:
        InputSearchPattern: 'containers\docker-compose.yaml'
        FindRegex: 'localhost:48700'
        ReplaceRegex: 'owlveydevops'
        UseUTF8: true
        UseRAW: true
    - task: DockerCompose@0
      displayName: Build 
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'OwlveyDevopsDocker'
        dockerComposeFile: './containers/docker-compose.yaml'
        action: 'Build services'        
        qualifyImageNames: true        
        includeLatestTag: true        
        additionalImageTags: 'V0.0.$(Build.BuildId)'
       
    - task: DockerCompose@0
      displayName: Publish
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'OwlveyDevopsDocker'
        dockerComposeFile: './containers/docker-compose.yaml'
        action: Push services
        qualifyImageNames: true
        includeLatestTag: true        
        additionalImageTags: 'V0.0.$(Build.BuildId)'
        
    
        
 
