name: $(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: commit
  jobs:    
  - job:    
    pool:
      vmImage: 'ubuntu-latest'        
    steps:
    - checkout: self            
    
    - task: DockerCompose@0
      displayName: Build 
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'OwlveyDevopsDocker'
        dockerComposeFile: './containers/docker-compose.yaml'
        action: 'Build services'        
        qualifyImageNames: false
        additionalImageTags: 'owlveydevops/authority'
       
    - task: DockerCompose@0
      displayName: Publish
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'OwlveyDevopsDocker'
        dockerComposeFile: './containers/docker-compose.yaml'
        action: Push services
        qualifyImageNames: false
        includeLatestTag: false        
        additionalImageTags: 'V0.0.$(Build.BuildId)'
        
    
        
 
