variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName:  Build
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - checkout: self        
    - bash: |
        pwd
        ls -a
        echo $(Build.BuildId)
      displayName: list folders   
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 3.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - script: dotnet restore 
      displayName: Restore Dependencies

    - script: dotnet publish src/Owlvey.Falcon.Authority.Presentation/Owlvey.Falcon.Authority.Presentation.csproj --no-restore -o /home/vsts/work/artifactory/bin/Publish
      displayName: Publish 

